# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'judgeProcess.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
import qdarkstyle
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication


class JudgeWidget(object):
    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(757, 764)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(180, -1, -1, 50)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioGroup_1 = QtWidgets.QButtonGroup(Dialog)
        self.radioButton_5 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_8.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioGroup_1.addButton(self.radioButton_5)
        self.radioGroup_1.addButton(self.radioButton_6)
        self.horizontalLayout_8.addWidget(self.radioButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioGroup_2 = QtWidgets.QButtonGroup(Dialog)
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_7.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioGroup_2.addButton(self.radioButton_3)
        self.radioGroup_2.addButton(self.radioButton_4)
        self.horizontalLayout_7.addWidget(self.radioButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.radioButton_9 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout_10.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioGroup_3 = QtWidgets.QButtonGroup(Dialog)
        self.radioGroup_3.addButton(self.radioButton_9)
        self.radioGroup_3.addButton(self.radioButton_10)
        self.horizontalLayout_10.addWidget(self.radioButton_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_11 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_11.setObjectName("radioButton_11")
        self.horizontalLayout_11.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioGroup_4 = QtWidgets.QButtonGroup(Dialog)
        self.radioGroup_4.addButton(self.radioButton_11)
        self.radioGroup_4.addButton(self.radioButton_12)
        self.horizontalLayout_11.addWidget(self.radioButton_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton = QtWidgets.QRadioButton(Dialog)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_6.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_6.addWidget(self.radioButton_2)
        self.radioGroup_5 = QtWidgets.QButtonGroup(Dialog)
        self.radioGroup_5.addButton(self.radioButton_2)
        self.radioGroup_5.addButton(self.radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_7 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout_9.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_9.addWidget(self.radioButton_8)
        self.radioGroup_6 = QtWidgets.QButtonGroup(Dialog)
        self.radioGroup_6.addButton(self.radioButton_7)
        self.radioGroup_6.addButton(self.radioButton_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.confirmButton = QtWidgets.QPushButton(Dialog)
        self.confirmButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.confirmButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setObjectName("pushButton_2")
        self.horizontalLayout_12.addWidget(self.cancelButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)

        self.retranslateUi(Dialog)
        self.bindButton()
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "诊断过程"))
        self.label_2.setText(_translate("Dialog", "1. 是否满足问题一？"))
        self.radioButton_5.setText(_translate("Dialog", "是"))
        self.radioButton_6.setText(_translate("Dialog", "否"))
        self.label_4.setText(_translate("Dialog", "2. 是否满足问题二？"))
        self.radioButton_3.setText(_translate("Dialog", "是"))
        self.radioButton_4.setText(_translate("Dialog", "否"))
        self.label_3.setText(_translate("Dialog", "3. 是否满足问题三？"))
        self.radioButton_9.setText(_translate("Dialog", "是"))
        self.radioButton_10.setText(_translate("Dialog", "否"))
        self.label_5.setText(_translate("Dialog", "4. 是否满足问题四？"))
        self.radioButton_11.setText(_translate("Dialog", "是"))
        self.radioButton_12.setText(_translate("Dialog", "否"))
        self.label_7.setText(_translate("Dialog", "5. 是否满足问题五？"))
        self.radioButton.setText(_translate("Dialog", "是"))
        self.radioButton_2.setText(_translate("Dialog", "否"))
        self.label_6.setText(_translate("Dialog", "6. 是否满足问题六？"))
        self.radioButton_7.setText(_translate("Dialog", "是"))
        self.radioButton_8.setText(_translate("Dialog", "否"))
        self.confirmButton.setText(_translate("Dialog", "提交"))
        self.cancelButton.setText(_translate("Dialog", "取消"))

    def bindButton(self):
        self.confirmButton.clicked.connect(self.confirmButtonEvent)
        self.cancelButton.clicked.connect(self.cancelButtonEvent)

    def cancelButtonEvent(self):
        self.Dialog.close()

    def confirmButtonEvent(self):
        list = []
        s = ""
        list.append(self.radioGroup_1.checkedButton().text())
        list.append(self.radioGroup_2.checkedButton().text())
        list.append(self.radioGroup_3.checkedButton().text())
        list.append(self.radioGroup_4.checkedButton().text())
        list.append(self.radioGroup_5.checkedButton().text())
        list.append(self.radioGroup_6.checkedButton().text())
        list.append(self.radioGroup_1.checkedButton().text())
        for i in range(len(list)):
            s += list[i]
        QtWidgets.QMessageBox.information(QtWidgets.QDialog(), "提示", s, QtWidgets.QMessageBox.Yes, QtWidgets.QMessageBox.Yes)
        self.Dialog.close()
        



if __name__ == "__main__":

    import sys

    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon("./Images/MainWindow_1.png"))
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    window = JudgeWidget()
    form = QtWidgets.QDialog()
    window.setupUi(form)
    form.show()

    sys.exit(app.exec_())