# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MWPrinter.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets, QtPrintSupport
from PyQt5.QtPrintSupport import QPageSetupDialog, QPrintDialog, QPrinter, QAbstractPrintDialog
from PyQt5.QtWidgets import QApplication, QWidget, QDialog, QMainWindow, QTextEdit



class MWPrinterWidget(object):

    def __init__(self):
        super(MWPrinterWidget, self).__init__()
        self.printer = QtPrintSupport.QPrinter()  # 定义一个默认的打印机


        self.Dialog = QDialog()
        self.Dialog.setObjectName("Dialog")
        self.Dialog.resize(1005, 767)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Dialog.setFont(font)

        # 设置样式表
        self.Dialog.setStyleSheet('background-color: rgb(255, 255, 255);\n color: rgb(0, 0, 0);')

        self.verticalLayout = QtWidgets.QVBoxLayout(self.Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, 30, 50, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.maintenanceWayID = QtWidgets.QLineEdit(self.Dialog)
        self.maintenanceWayID.setObjectName("maintenanceWayID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayID)
        self.Label_3 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_3.setFont(font)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.maintenanceWayName = QtWidgets.QLineEdit(self.Dialog)
        self.maintenanceWayName.setObjectName("maintenanceWayName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayName)
        self.Label_5 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_5.setFont(font)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.firstTime = QtWidgets.QLineEdit(self.Dialog)
        self.firstTime.setObjectName("firstTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firstTime)
        self.Label_7 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_7.setFont(font)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.recentTime = QtWidgets.QLineEdit(self.Dialog)
        self.recentTime.setObjectName("recentTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.recentTime)
        self.Label_13 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_13.setFont(font)
        self.Label_13.setObjectName("Label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.alterRule = QtWidgets.QLineEdit(self.Dialog)
        self.alterRule.setObjectName("alterRule")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.alterRule)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_2 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_2.setFont(font)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.productID = QtWidgets.QLineEdit(self.Dialog)
        self.productID.setObjectName("productID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productID)
        self.Label_4 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_4.setFont(font)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.productName = QtWidgets.QLineEdit(self.Dialog)
        self.productName.setEnabled(True)
        self.productName.setReadOnly(False)
        self.productName.setObjectName("productName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productName)
        self.Label_6 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_6.setFont(font)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.productNO = QtWidgets.QLineEdit(self.Dialog)
        self.productNO.setObjectName("productNO")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.productNO)
        self.Label_8 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_8.setFont(font)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.interval = QtWidgets.QLineEdit(self.Dialog)
        self.interval.setObjectName("interval")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.interval)
        self.Label_14 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_14.setFont(font)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.remark = QtWidgets.QLineEdit(self.Dialog)
        self.remark.setObjectName("remark")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.remark)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(50, 10, 50, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.operation = QtWidgets.QTextEdit(self.Dialog)
        self.operation.setMinimumSize(QtCore.QSize(0, 300))
        self.operation.setObjectName("operation")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.operation)
        self.Label_15 = QtWidgets.QLabel(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_15.setFont(font)
        self.Label_15.setObjectName("Label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.conserveButton = QtWidgets.QPushButton(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.conserveButton.setFont(font)
        self.conserveButton.setObjectName("conserveButton")
        self.horizontalLayout_2.addWidget(self.conserveButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.cancelButton = QtWidgets.QPushButton(self.Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(self.Dialog)

        # 绑定按钮
        self.bindbutton()

        QtCore.QMetaObject.connectSlotsByName(self.Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "打印维保方式"))
        self.Label.setText(_translate("Dialog", "维保方式编号："))
        self.Label_3.setText(_translate("Dialog", "维保方式名称："))
        self.Label_5.setText(_translate("Dialog", "初次维保时间："))
        self.Label_7.setText(_translate("Dialog", "最近维保时间："))
        self.Label_13.setText(_translate("Dialog", "维保到期提醒："))
        self.Label_2.setText(_translate("Dialog", "产品编号："))
        self.Label_4.setText(_translate("Dialog", "产品名称："))
        self.Label_6.setText(_translate("Dialog", "产品代号："))
        self.Label_8.setText(_translate("Dialog", "维保时间间隔："))
        self.Label_14.setText(_translate("Dialog", "备注："))
        self.Label_15.setText(_translate("Dialog", "维保操作说明："))
        self.conserveButton.setText(_translate("Dialog", "打印设置"))
        self.cancelButton.setText(_translate("Dialog", "开始打印"))
        self.conserveButton.setVisible(False)
        self.cancelButton.setVisible(False)


        self.maintenanceWayID.setEnabled(False)
        self.maintenanceWayName.setEnabled(False)
        self.productID.setEnabled(False)
        self.productName.setEnabled(False)
        self.productNO.setEnabled(False)
        self.firstTime.setEnabled(False)
        self.recentTime.setEnabled(False)
        self.interval.setEnabled(False)
        self.alterRule.setEnabled(False)
        self.operation.setEnabled(False)
        self.remark.setEnabled(False)

    def bindbutton(self):
        # 绑定按钮
        self.conserveButton.clicked.connect(self.showsettingdailog)
        self.cancelButton.clicked.connect(self.showprintdialog)


    def setData(self, list):
        """
        hsj 设置单个产品查询结果
        :param list: 单个查询结果
        :return:
        """
        self.maintenanceWayID.setText(list[0])
        self.maintenanceWayName.setText(list[1])
        self.productID.setText(list[2])
        self.productName.setText(list[3])
        self.productNO.setText(list[4])
        self.firstTime.setText(list[5])
        self.recentTime.setText(list[6])
        self.interval.setText(list[7])
        self.alterRule.setText(list[8])
        self.operation.setText(list[13])
        self.remark.setText(list[14])
        self.label.setText("维保方式")

    # 显示打印设置对话框
    def showsettingdailog(self):
        try:
            printerdailog = QPageSetupDialog(self.printer)
            #print(self.Dialog.geometry().width(), self.Dialog.geometry().height())
            printerdailog.exec()
        except Exception as e:
            print(e)

    # 显示打印对话框
    def showprintdialog(self):
        try:
            # 将绘制的目标重新定向到打印机
            print1 = QPrintDialog(self.printer, self.Dialog)
            if QDialog.Accepted == print1.exec():
                painter = QtGui.QPainter()
                # 将绘制的目标重新定向到打印机
                painter.begin(self.printer)
                self.Dialog.resize(self.Dialog.geometry().width(), self.Dialog.geometry().height())

                self.label.setText("维保方式")

                self.conserveButton.setVisible(False)
                self.cancelButton.setVisible(False)
                screen = self.Dialog.grab()
                painter.drawPixmap(0, 0, self.Dialog.geometry().width(), self.Dialog.geometry().height(), screen)
                # painter.end()
                #print("print")
                self.conserveButton.setVisible(False)
                self.cancelButton.setVisible(False)

                self.label.setText("打印维保方式")
                self.Dialog.close()

        # painter.drawPixmap(100,100, )
        except Exception as e:
            print(e)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = MWPrinterWidget()
    w.Dialog.show()
    sys.exit(app.exec_())