# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectSingleMR.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class SelectSingleMRWidget(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # 设置长、宽
        Dialog.resize(811, 904)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)

        # 设置全局字体
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        Dialog.setFont(font)

        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.errorMessage = QtWidgets.QLabel(Dialog)
        self.errorMessage.setStyleSheet("color: rgb(255, 0, 0);")
        self.errorMessage.setObjectName("errorMessage")
        self.verticalLayout.addWidget(self.errorMessage)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 8, 24)
        self.gridLayout.setHorizontalSpacing(26)
        self.gridLayout.setVerticalSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        self.Label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_2.setFont(font)
        self.Label_2.setObjectName("Label_2")
        self.gridLayout.addWidget(self.Label_2, 3, 0, 1, 1)
        self.updateName = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateName.sizePolicy().hasHeightForWidth())
        self.updateName.setSizePolicy(sizePolicy)
        self.updateName.setObjectName("updateName")
        self.gridLayout.addWidget(self.updateName, 5, 3, 1, 1)
        self.creator = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.creator.sizePolicy().hasHeightForWidth())
        self.creator.setSizePolicy(sizePolicy)
        self.creator.setObjectName("creator")
        self.gridLayout.addWidget(self.creator, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.Label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_11.setFont(font)
        self.Label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_11.setObjectName("Label_11")
        self.gridLayout.addWidget(self.Label_11, 6, 2, 1, 1)
        self.Label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_4.setFont(font)
        self.Label_4.setObjectName("Label_4")
        self.gridLayout.addWidget(self.Label_4, 4, 0, 1, 1)
        self.mwName = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwName.sizePolicy().hasHeightForWidth())
        self.mwName.setSizePolicy(sizePolicy)
        self.mwName.setObjectName("mwName")
        self.gridLayout.addWidget(self.mwName, 2, 1, 1, 1)
        self.Label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_10.setFont(font)
        self.Label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_10.setObjectName("Label_10")
        self.gridLayout.addWidget(self.Label_10, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.productModelIDLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.productModelIDLabel.setFont(font)
        self.productModelIDLabel.setObjectName("productModelIDLabel")
        self.gridLayout.addWidget(self.productModelIDLabel, 2, 0, 1, 1)
        self.Label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.gridLayout.addWidget(self.Label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.mrResult = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrResult.sizePolicy().hasHeightForWidth())
        self.mrResult.setSizePolicy(sizePolicy)
        self.mrResult.setObjectName("mrResult")
        self.gridLayout.addWidget(self.mrResult, 4, 3, 1, 1)
        self.mrTime = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrTime.sizePolicy().hasHeightForWidth())
        self.mrTime.setSizePolicy(sizePolicy)
        self.mrTime.setObjectName("mrTime")
        self.gridLayout.addWidget(self.mrTime, 3, 1, 1, 1)
        self.Label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_7.setFont(font)
        self.Label_7.setObjectName("Label_7")
        self.gridLayout.addWidget(self.Label_7, 5, 0, 1, 1)
        self.Label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_9.setFont(font)
        self.Label_9.setObjectName("Label_9")
        self.gridLayout.addWidget(self.Label_9, 6, 0, 1, 1)
        self.Label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_3.setFont(font)
        self.Label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_3.setObjectName("Label_3")
        self.gridLayout.addWidget(self.Label_3, 3, 2, 1, 1)
        self.createTime = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createTime.sizePolicy().hasHeightForWidth())
        self.createTime.setSizePolicy(sizePolicy)
        self.createTime.setObjectName("createTime")
        self.gridLayout.addWidget(self.createTime, 6, 1, 1, 1)
        self.updateTime = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTime.sizePolicy().hasHeightForWidth())
        self.updateTime.setSizePolicy(sizePolicy)
        self.updateTime.setObjectName("updateTime")
        self.gridLayout.addWidget(self.updateTime, 6, 3, 1, 1)
        self.mrID = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrID.sizePolicy().hasHeightForWidth())
        self.mrID.setSizePolicy(sizePolicy)
        self.mrID.setText("")
        self.mrID.setObjectName("mrID")
        self.gridLayout.addWidget(self.mrID, 0, 1, 1, 1)
        self.productName = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productName.sizePolicy().hasHeightForWidth())
        self.productName.setSizePolicy(sizePolicy)
        self.productName.setObjectName("productName")
        self.gridLayout.addWidget(self.productName, 1, 3, 1, 1)
        self.productNO = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productNO.sizePolicy().hasHeightForWidth())
        self.productNO.setSizePolicy(sizePolicy)
        self.productNO.setObjectName("productNO")
        self.gridLayout.addWidget(self.productNO, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.Label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_6.setFont(font)
        self.Label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Label_6.setObjectName("Label_6")
        self.gridLayout.addWidget(self.Label_6, 4, 2, 1, 1)
        self.mrPart = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrPart.sizePolicy().hasHeightForWidth())
        self.mrPart.setSizePolicy(sizePolicy)
        self.mrPart.setObjectName("mrPart")
        self.gridLayout.addWidget(self.mrPart, 3, 3, 1, 1)
        self.mrLead = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mrLead.sizePolicy().hasHeightForWidth())
        self.mrLead.setSizePolicy(sizePolicy)
        self.mrLead.setObjectName("mrLead")
        self.gridLayout.addWidget(self.mrLead, 4, 1, 1, 1)
        self.mwID = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mwID.sizePolicy().hasHeightForWidth())
        self.mwID.setSizePolicy(sizePolicy)
        self.mwID.setObjectName("mwID")
        self.gridLayout.addWidget(self.mwID, 1, 1, 1, 1)
        self.productID = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productID.sizePolicy().hasHeightForWidth())
        self.productID.setSizePolicy(sizePolicy)
        self.productID.setObjectName("productID")
        self.gridLayout.addWidget(self.productID, 0, 3, 1, 1)

        # 技术文档
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.documentPathButton = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.documentPathButton.sizePolicy().hasHeightForWidth())
        self.documentPathButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.documentPathButton.setFont(font)
        self.documentPathButton.setObjectName("documentPathButton")
        self.gridLayout.addWidget(self.documentPathButton, 7, 1, 1, 1)

        # 备注
        self.remarkLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.remarkLabel.setFont(font)
        self.remarkLabel.setObjectName("remarkLabel")
        self.gridLayout.addWidget(self.remarkLabel, 8, 0, 1, 1)
        self.remark = QtWidgets.QTextEdit(Dialog)
        self.remark.setObjectName("remark")
        self.gridLayout.addWidget(self.remark, 8, 1, 1, 3)

        self.gridLayout.setRowMinimumHeight(0, 30)
        self.gridLayout.setRowMinimumHeight(1, 30)
        self.gridLayout.setRowMinimumHeight(2, 30)
        self.gridLayout.setRowMinimumHeight(3, 30)
        self.gridLayout.setRowMinimumHeight(4, 30)
        self.gridLayout.setRowMinimumHeight(5, 30)
        self.gridLayout.setRowMinimumHeight(6, 30)
        self.gridLayout.setRowMinimumHeight(7, 30)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        # self.conserveButton = QtWidgets.QPushButton(Dialog)
        # font = QtGui.QFont()
        # font.setFamily("微软雅黑 Light")
        # font.setPointSize(10)
        # self.conserveButton.setFont(font)
        # self.conserveButton.setObjectName("conserveButton")
        # self.horizontalLayout.addWidget(self.conserveButton)
        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout.addItem(spacerItem1)
        # self.cancelButton = QtWidgets.QPushButton(Dialog)
        # font = QtGui.QFont()
        # font.setFamily("微软雅黑 Light")
        # font.setPointSize(10)
        # self.cancelButton.setFont(font)
        # self.cancelButton.setObjectName("cancelButton")
        # self.horizontalLayout.addWidget(self.cancelButton)
        # spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout.addItem(spacerItem2)
        # self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "查看维保方式记录"))
        # self.errorMessage.setText(_translate("Dialog", "s"))
        self.Label_2.setText(_translate("Dialog", "维保时间："))
        self.label_5.setText(_translate("Dialog", "产品别名："))
        self.Label_11.setText(_translate("Dialog", "更新时间："))
        self.Label_4.setText(_translate("Dialog", "维保负责人："))
        self.Label_10.setText(_translate("Dialog", "更新人员："))
        self.label_2.setText(_translate("Dialog", "维保方式编号:"))
        self.productModelIDLabel.setText(_translate("Dialog", "维保方式名称："))
        self.Label.setText(_translate("Dialog", "维保记录编号："))
        self.label_3.setText(_translate("Dialog", "产品名称："))
        self.Label_7.setText(_translate("Dialog", "创建人员："))
        self.Label_9.setText(_translate("Dialog", "创建时间："))
        self.Label_3.setText(_translate("Dialog", "维保部位："))
        self.label_6.setText(_translate("Dialog", "技术文档："))
        self.remarkLabel.setText(_translate("Dialog", "备注："))
        self.label_4.setText(_translate("Dialog", "产品编号："))
        self.Label_6.setText(_translate("Dialog", "维保效果："))
        # self.conserveButton.setText(_translate("Dialog", "保存"))
        # self.cancelButton.setText(_translate("Dialog", "取消"))

    #     设置按钮隐藏
    #     self.conserveButton.setVisible(False)
    #     self.cancelButton.setVisible(False)

        # self.mrID.setEnabled(False)
        # self.productID.setEnabled(False)
        # self.productName.setEnabled(False)
        # self.productNO.setEnabled(False)
        # self.mwID.setEnabled(False)
        # self.mwName.setEnabled(False)
        # self.mrTime.setEnabled(False)
        # self.mrPart.setEnabled(False)
        # self.mrLead.setEnabled(False)
        # self.mrResult.setEnabled(False)
        # self.creator.setEnabled(False)
        # self.createTime.setEnabled(False)
        # self.updateName.setEnabled(False)
        # self.updateTime.setEnabled(False)
        # self.remark.setEnabled(False)


    def setData(self, list):
        """
        hsj 设置单个产品查询结果
        :param list: 单个查询结果
        :return:
        """
        self.mrID.setText(list[0])
        self.productID.setText(list[1])
        self.productName.setText(list[2])
        self.productNO.setText(list[3])
        self.mwID.setText(list[4])
        self.mwName.setText(list[5])
        self.mrTime.setText(list[6])
        self.mrPart.setText(list[7])
        self.mrLead.setText(list[8])
        self.mrResult.setText(list[9])
        self.creator.setText(list[10])
        self.createTime.setText(list[11])
        self.updateName.setText(list[12])
        self.updateTime.setText(list[13])
        self.documentPathButton.setText(list[14])
        self.remark.setText(list[15])


if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QWidget()
    w = SelectSingleMRWidget()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())