# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectSingleMW.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class SelectSingleMWWidget(object):
    #print("selectsinglemwwidget方法执行了。。。。")

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1005, 767)

        # 设置全局字体
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        Dialog.setFont(font)

        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(50, 30, 50, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(Dialog)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.maintenanceWayID = QtWidgets.QLineEdit(Dialog)
        self.maintenanceWayID.setObjectName("maintenanceWayID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayID)
        self.Label_3 = QtWidgets.QLabel(Dialog)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.maintenanceWayName = QtWidgets.QLineEdit(Dialog)
        self.maintenanceWayName.setObjectName("maintenanceWayName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maintenanceWayName)
        self.Label_5 = QtWidgets.QLabel(Dialog)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.Label_7 = QtWidgets.QLabel(Dialog)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.Label_9 = QtWidgets.QLabel(Dialog)
        self.Label_9.setObjectName("Label_9")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.creator = QtWidgets.QLineEdit(Dialog)
        self.creator.setObjectName("creator")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.creator)
        self.Label_11 = QtWidgets.QLabel(Dialog)
        self.Label_11.setObjectName("Label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.updateName = QtWidgets.QLineEdit(Dialog)
        self.updateName.setObjectName("updateName")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.updateName)
        self.Label_13 = QtWidgets.QLabel(Dialog)
        self.Label_13.setObjectName("Label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.alterRule = QtWidgets.QLineEdit(Dialog)
        self.alterRule.setObjectName("alterRule")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.alterRule)
        self.recentTime = QtWidgets.QLineEdit(Dialog)
        self.recentTime.setObjectName("recentTime")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.recentTime)
        self.firstTime = QtWidgets.QLineEdit(Dialog)
        self.firstTime.setObjectName("firstTime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.firstTime)
        self.horizontalLayout.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_2 = QtWidgets.QLabel(Dialog)
        self.Label_2.setObjectName("Label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.Label_4 = QtWidgets.QLabel(Dialog)
        self.Label_4.setObjectName("Label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.productName = QtWidgets.QLineEdit(Dialog)
        self.productName.setEnabled(True)
        self.productName.setReadOnly(False)
        self.productName.setObjectName("productName")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.productName)
        self.Label_6 = QtWidgets.QLabel(Dialog)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.productNO = QtWidgets.QLineEdit(Dialog)
        self.productNO.setObjectName("productNO")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.productNO)
        self.Label_8 = QtWidgets.QLabel(Dialog)
        self.Label_8.setObjectName("Label_8")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.interval = QtWidgets.QLineEdit(Dialog)
        self.interval.setObjectName("interval")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.interval)
        self.Label_10 = QtWidgets.QLabel(Dialog)
        self.Label_10.setObjectName("Label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.Label_12 = QtWidgets.QLabel(Dialog)
        self.Label_12.setObjectName("Label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.Label_14 = QtWidgets.QLabel(Dialog)
        self.Label_14.setObjectName("Label_14")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_14)
        self.remark = QtWidgets.QLineEdit(Dialog)
        self.remark.setObjectName("remark")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.remark)
        self.productID = QtWidgets.QLineEdit(Dialog)
        self.productID.setObjectName("productID")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productID)
        self.createTime = QtWidgets.QLineEdit(Dialog)
        self.createTime.setObjectName("createTime")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.createTime)
        self.updateTime = QtWidgets.QLineEdit(Dialog)
        self.updateTime.setObjectName("updateTime")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.updateTime)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(50, 10, 50, -1)
        self.formLayout_3.setObjectName("formLayout_3")
        self.operation = QtWidgets.QTextEdit(Dialog)
        self.operation.setMinimumSize(QtCore.QSize(0, 300))
        self.operation.setObjectName("operation")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.operation)
        self.Label_15 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.Label_15.setFont(font)
        self.Label_15.setObjectName("Label_15")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_15)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        # self.conserveButton = QtWidgets.QPushButton(Dialog)
        # self.conserveButton.setObjectName("conserveButton")
        # self.horizontalLayout_2.addWidget(self.conserveButton)
        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout_2.addItem(spacerItem1)
        # self.cancelButton = QtWidgets.QPushButton(Dialog)
        # self.cancelButton.setObjectName("cancelButton")
        # self.horizontalLayout_2.addWidget(self.cancelButton)
        # spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout_2.addItem(spacerItem2)
        # self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "查看维保方式"))
        self.Label.setText(_translate("Dialog", "维保方式编号："))
        self.Label_3.setText(_translate("Dialog", "维保方式名称："))
        self.Label_5.setText(_translate("Dialog", "初次维保时间："))
        self.Label_7.setText(_translate("Dialog", "最近维保时间："))
        self.Label_9.setText(_translate("Dialog", "创建人员："))
        self.Label_11.setText(_translate("Dialog", "修改人员："))
        self.Label_13.setText(_translate("Dialog", "维保到期提醒："))
        self.Label_2.setText(_translate("Dialog", "产品编号："))
        self.Label_4.setText(_translate("Dialog", "产品名称："))
        self.Label_6.setText(_translate("Dialog", "产品代号："))
        self.Label_8.setText(_translate("Dialog", "维保时间间隔："))
        self.Label_10.setText(_translate("Dialog", "创建时间："))
        self.Label_12.setText(_translate("Dialog", "修改时间："))
        self.Label_14.setText(_translate("Dialog", "备注："))
        self.Label_15.setText(_translate("Dialog", "维保操作说明："))
        # self.conserveButton.setText(_translate("Dialog", "保存"))
        # self.cancelButton.setText(_translate("Dialog", "取消"))


        # self.maintenanceWayID.setEnabled(False)
        # self.maintenanceWayName.setEnabled(False)
        # self.productID.setEnabled(False)
        # self.productName.setEnabled(False)
        # self.productNO.setEnabled(False)
        # self.firstTime.setEnabled(False)
        # self.recentTime.setEnabled(False)
        # self.interval.setEnabled(False)
        # self.alterRule.setEnabled(False)
        # self.creator.setEnabled(False)
        # self.createTime.setEnabled(False)
        # self.updateName.setEnabled(False)
        # self.updateTime.setEnabled(False)
        # self.operation.setEnabled(False)
        # self.remark.setEnabled(False)

    def setData(self, list):
        """
        hsj 设置单个产品查询结果
        :param list: 单个查询结果
        :return:
        """
        self.maintenanceWayID.setText(list[0])
        self.maintenanceWayName.setText(list[1])
        self.productID.setText(list[2])
        self.productName.setText(list[3])
        self.productNO.setText(list[4])
        self.firstTime.setText(list[5])
        self.recentTime.setText(list[6])
        self.interval.setText(list[7])
        self.alterRule.setText(list[8])
        self.creator.setText(list[9])
        self.createTime.setText(list[10])
        self.updateName.setText(list[11])
        self.updateTime.setText(list[12])
        self.operation.setText(list[13])
        self.remark.setText(list[14])

if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QWidget()
    w = SelectSingleMWWidget()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())