# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SelectSingleProductView.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class SelectSingleProductWidget(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(726, 778)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(50, 20, 50, -1)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(Dialog)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.productNO = QtWidgets.QLineEdit(Dialog)
        self.productNO.setEnabled(False)
        self.productNO.setObjectName("productNO")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.productNO)
        self.iDLabel = QtWidgets.QLabel(Dialog)
        self.iDLabel.setObjectName("iDLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iDLabel)
        self.ID = QtWidgets.QLineEdit(Dialog)
        self.ID.setEnabled(False)
        self.ID.setObjectName("ID")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ID)
        self.Label_2 = QtWidgets.QLabel(Dialog)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.productModelID = QtWidgets.QLineEdit(Dialog)
        self.productModelID.setEnabled(False)
        self.productModelID.setObjectName("productModelID")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.productModelID)
        self.Label_3 = QtWidgets.QLabel(Dialog)
        self.Label_3.setObjectName("Label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Label_3)
        self.life = QtWidgets.QLineEdit(Dialog)
        self.life.setEnabled(False)
        self.life.setObjectName("life")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.life)
        self.Label_4 = QtWidgets.QLabel(Dialog)
        self.Label_4.setObjectName("Label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Label_4)
        self.startDate = QtWidgets.QLineEdit(Dialog)
        self.startDate.setEnabled(False)
        self.startDate.setObjectName("startDate")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.startDate)
        self.Label_5 = QtWidgets.QLabel(Dialog)
        self.Label_5.setObjectName("Label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.daysBefore = QtWidgets.QLineEdit(Dialog)
        self.daysBefore.setEnabled(False)
        self.daysBefore.setObjectName("daysBefore")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.daysBefore)
        self.Label_13 = QtWidgets.QLabel(Dialog)
        self.Label_13.setObjectName("Label_13")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Label_13)
        self.isUsedCountLimit = QtWidgets.QLineEdit(Dialog)
        self.isUsedCountLimit.setEnabled(False)
        self.isUsedCountLimit.setObjectName("isUsedCountLimit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.isUsedCountLimit)
        self.Label_6 = QtWidgets.QLabel(Dialog)
        self.Label_6.setObjectName("Label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.maxUsedCount = QtWidgets.QLineEdit(Dialog)
        self.maxUsedCount.setEnabled(False)
        self.maxUsedCount.setObjectName("maxUsedCount")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.maxUsedCount)
        self.Label_7 = QtWidgets.QLabel(Dialog)
        self.Label_7.setObjectName("Label_7")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Label_7)
        self.havaUsedCount = QtWidgets.QLineEdit(Dialog)
        self.havaUsedCount.setEnabled(False)
        self.havaUsedCount.setObjectName("havaUsedCount")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.havaUsedCount)
        self.Label_8 = QtWidgets.QLabel(Dialog)
        self.Label_8.setObjectName("Label_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.Label_8)
        self.createID = QtWidgets.QLineEdit(Dialog)
        self.createID.setEnabled(False)
        self.createID.setObjectName("createID")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.createID)
        self.Label_9 = QtWidgets.QLabel(Dialog)
        self.Label_9.setObjectName("Label_9")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.Label_9)
        self.createTime = QtWidgets.QLineEdit(Dialog)
        self.createTime.setEnabled(False)
        self.createTime.setObjectName("createTime")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.createTime)
        self.Label_10 = QtWidgets.QLabel(Dialog)
        self.Label_10.setObjectName("Label_10")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.Label_10)
        self.updateID = QtWidgets.QLineEdit(Dialog)
        self.updateID.setEnabled(False)
        self.updateID.setObjectName("updateID")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.updateID)
        self.Label_11 = QtWidgets.QLabel(Dialog)
        self.Label_11.setObjectName("Label_11")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.Label_11)
        self.updateTime = QtWidgets.QLineEdit(Dialog)
        self.updateTime.setEnabled(False)
        self.updateTime.setObjectName("updateTime")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.updateTime)
        self.Label_12 = QtWidgets.QLabel(Dialog)
        self.Label_12.setObjectName("Label_12")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.Label_12)
        self.remark = QtWidgets.QTextEdit(Dialog)
        self.remark.setEnabled(False)
        self.remark.setObjectName("remark")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.remark)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "产品信息查看"))
        self.Label.setText(_translate("Dialog", "产品编号："))
        self.iDLabel.setText(_translate("Dialog", "ID:"))
        self.Label_2.setText(_translate("Dialog", "产品模型ID："))
        self.Label_3.setText(_translate("Dialog", "寿命(天)："))
        self.Label_4.setText(_translate("Dialog", "寿命起始时间："))
        self.Label_5.setText(_translate("Dialog", "距到期提醒(天)："))
        self.Label_13.setText(_translate("Dialog", "使用次数限制："))
        self.Label_6.setText(_translate("Dialog", "最多使用次数："))
        self.Label_7.setText(_translate("Dialog", "已使用次数："))
        self.Label_8.setText(_translate("Dialog", "创建人员："))
        self.Label_9.setText(_translate("Dialog", "创建时间："))
        self.Label_10.setText(_translate("Dialog", "修改人员："))
        self.Label_11.setText(_translate("Dialog", "修改时间："))
        self.Label_12.setText(_translate("Dialog", "备注："))

    def setData(self, list):
        """
        hsj 设置单个产品查询结果
        :param list: 单个查询结果
        :return:
        """
        self.productNO.setText(list[0])
        self.life.setText(list[1])
        self.startDate.setText(list[2])
        self.daysBefore.setText(list[3])
        self.isUsedCountLimit.setText(list[4])
        self.maxUsedCount.setText(list[5])
        self.havaUsedCount.setText(list[6])
        self.createID.setText(list[7])
        self.createTime.setText(list[8])
        self.updateID.setText(list[9])
        self.updateTime.setText(list[10])
        self.remark.setText(list[11])

if __name__ == "__main__":
    app = QApplication(sys.argv)
    form = QWidget()
    w = SelectSingleProductWidget()
    w.setupUi(form)
    form.show()
    sys.exit(app.exec_())